// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj2EFg8BGSfElEAkteu4J5rNHmn92tZas',
    appId: '1:348169985840:web:9dd6bfe92498f35649b2f5',
    messagingSenderId: '348169985840',
    projectId: 'opti-meal-7c233',
    authDomain: 'opti-meal-7c233.firebaseapp.com',
    storageBucket: 'opti-meal-7c233.firebasestorage.app',
    measurementId: 'G-HBCC5GLJTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Is64jZYBJCXLz_wtnf4YQtH0CseR-qk',
    appId: '1:348169985840:android:f20b283ed57c914549b2f5',
    messagingSenderId: '348169985840',
    projectId: 'opti-meal-7c233',
    storageBucket: 'opti-meal-7c233.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9CcwjRCykc6io9D-L9v40YHLsz0LIUuE',
    appId: '1:348169985840:ios:890364d090aaacc649b2f5',
    messagingSenderId: '348169985840',
    projectId: 'opti-meal-7c233',
    storageBucket: 'opti-meal-7c233.firebasestorage.app',
    iosBundleId: 'com.example.optimeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9CcwjRCykc6io9D-L9v40YHLsz0LIUuE',
    appId: '1:348169985840:ios:890364d090aaacc649b2f5',
    messagingSenderId: '348169985840',
    projectId: 'opti-meal-7c233',
    storageBucket: 'opti-meal-7c233.firebasestorage.app',
    iosBundleId: 'com.example.optimeal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj2EFg8BGSfElEAkteu4J5rNHmn92tZas',
    appId: '1:348169985840:web:570a6807ced4c1fa49b2f5',
    messagingSenderId: '348169985840',
    projectId: 'opti-meal-7c233',
    authDomain: 'opti-meal-7c233.firebaseapp.com',
    storageBucket: 'opti-meal-7c233.firebasestorage.app',
    measurementId: 'G-KDSB216TZK',
  );
}
